"""
train_model.py
---------------
End-to-end training pipeline for the phishing-URL classifier.

Steps:
  1. Load dataset/phishing_dataset.csv (generated by generate_dataset.py,
     or a user-supplied real dataset with the same schema).
  2. Clean: drop duplicates, handle missing values.
  3. Split into train/test sets (stratified).
  4. Scale numeric features (StandardScaler) -- required by KNN/SVM/LogReg.
  5. Train 8 candidate algorithms.
  6. Score every model on accuracy / precision / recall / F1 / ROC-AUC.
  7. Persist the best model + scaler + metadata + comparison chart.

Run:  python train_model.py
"""

import json
import os
import time
import warnings

import joblib
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import (
    accuracy_score, precision_score, recall_score, f1_score,
    roc_auc_score, confusion_matrix,
)

from feature_extractor import FEATURE_NAMES

warnings.filterwarnings("ignore")

BASE_DIR = os.path.dirname(__file__)
DATASET_PATH = os.path.join(BASE_DIR, "dataset", "phishing_dataset.csv")
MODELS_DIR = os.path.join(BASE_DIR, "models")
STATIC_IMG_DIR = os.path.join(BASE_DIR, "static", "images")

os.makedirs(MODELS_DIR, exist_ok=True)
os.makedirs(STATIC_IMG_DIR, exist_ok=True)

# Optional gradient-boosting libraries -- included in requirements.txt but
# not required for the pipeline to run, since not every grading machine
# will have them preinstalled.
try:
    from xgboost import XGBClassifier
    XGB_AVAILABLE = True
except ImportError:
    XGB_AVAILABLE = False

try:
    from lightgbm import LGBMClassifier
    LGBM_AVAILABLE = True
except ImportError:
    LGBM_AVAILABLE = False


def load_and_clean(path):
    df = pd.read_csv(path)

    before = len(df)
    df = df.drop_duplicates(subset=["url"] + FEATURE_NAMES)
    dropped_dupes = before - len(df)

    missing_before = df.isnull().sum().sum()
    for col in FEATURE_NAMES:
        if df[col].isnull().any():
            df[col] = df[col].fillna(df[col].median())
    df = df.dropna(subset=["label"])

    df["label"] = df["label"].str.strip().str.lower()
    df = df[df["label"].isin(["safe", "phishing"])]

    print(f"[clean] rows before={before}, dropped duplicates={dropped_dupes}, "
          f"missing values imputed={int(missing_before)}, final rows={len(df)}")
    return df


def build_models():
    models = {
        "Logistic Regression": LogisticRegression(max_iter=1000, random_state=42),
        "Decision Tree": DecisionTreeClassifier(max_depth=10, random_state=42),
        "Random Forest": RandomForestClassifier(n_estimators=200, max_depth=12, random_state=42, n_jobs=-1),
        "KNN": KNeighborsClassifier(n_neighbors=7),
        "SVM": SVC(kernel="rbf", probability=True, random_state=42),
        "Naive Bayes": GaussianNB(),
    }
    if XGB_AVAILABLE:
        models["XGBoost"] = XGBClassifier(
            n_estimators=250, max_depth=6, learning_rate=0.1,
            use_label_encoder=False, eval_metric="logloss", random_state=42,
        )
    if LGBM_AVAILABLE:
        models["LightGBM"] = LGBMClassifier(n_estimators=250, max_depth=6, random_state=42, verbose=-1)
    return models


def evaluate(model, X_test, y_test):
    preds = model.predict(X_test)
    probs = model.predict_proba(X_test)[:, 1] if hasattr(model, "predict_proba") else preds
    return {
        "accuracy": accuracy_score(y_test, preds),
        "precision": precision_score(y_test, preds),
        "recall": recall_score(y_test, preds),
        "f1": f1_score(y_test, preds),
        "roc_auc": roc_auc_score(y_test, probs),
    }


def plot_comparison(results, out_path):
    names = list(results.keys())
    f1s = [results[n]["f1"] for n in names]
    accs = [results[n]["accuracy"] for n in names]

    x = np.arange(len(names))
    width = 0.35

    fig, ax = plt.subplots(figsize=(10, 5.5))
    ax.bar(x - width / 2, accs, width, label="Accuracy", color="#2dd4bf")
    ax.bar(x + width / 2, f1s, width, label="F1 Score", color="#7c5cff")
    ax.set_xticks(x)
    ax.set_xticklabels(names, rotation=30, ha="right")
    ax.set_ylim(0, 1.05)
    ax.set_ylabel("Score")
    ax.set_title("Model Comparison — Accuracy vs F1 Score")
    ax.legend()
    fig.tight_layout()
    fig.savefig(out_path, dpi=150, transparent=False, facecolor="#0b0e14")
    plt.close(fig)


def plot_feature_importance(model, feature_names, out_path):
    importances = None
    if hasattr(model, "feature_importances_"):
        importances = model.feature_importances_
    elif hasattr(model, "coef_"):
        importances = np.abs(model.coef_[0])

    if importances is None:
        return None

    order = np.argsort(importances)[::-1]
    names_sorted = [feature_names[i] for i in order]
    vals_sorted = importances[order]

    fig, ax = plt.subplots(figsize=(9, 6))
    ax.barh(names_sorted[::-1], vals_sorted[::-1], color="#00e5c7")
    ax.set_xlabel("Importance")
    ax.set_title("Feature Importance — Best Model")
    fig.tight_layout()
    fig.savefig(out_path, dpi=150, facecolor="#0b0e14")
    plt.close(fig)

    return {name: float(val) for name, val in zip(names_sorted, vals_sorted)}


def main():
    if not os.path.exists(DATASET_PATH):
        raise FileNotFoundError(
            "Dataset not found. Run `python generate_dataset.py` first, "
            "or place a real phishing_dataset.csv in the dataset/ folder."
        )

    df = load_and_clean(DATASET_PATH)

    X = df[FEATURE_NAMES].astype(float)
    y = (df["label"] == "phishing").astype(int)

    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.2, random_state=42, stratify=y
    )

    scaler = StandardScaler()
    X_train_scaled = scaler.fit_transform(X_train)
    X_test_scaled = scaler.transform(X_test)

    models = build_models()
    results = {}
    trained = {}

    print(f"\n[train] {len(models)} candidate models on {len(X_train)} training rows "
          f"({len(FEATURE_NAMES)} features)\n")

    for name, model in models.items():
        start = time.time()
        model.fit(X_train_scaled, y_train)
        elapsed = time.time() - start
        metrics = evaluate(model, X_test_scaled, y_test)
        metrics["train_seconds"] = round(elapsed, 3)
        results[name] = metrics
        trained[name] = model
        print(f"  - {name:<22} acc={metrics['accuracy']:.4f}  f1={metrics['f1']:.4f}  "
              f"roc_auc={metrics['roc_auc']:.4f}  ({elapsed:.2f}s)")

    best_name = max(results, key=lambda n: results[n]["f1"])
    best_model = trained[best_name]
    best_metrics = results[best_name]
    print(f"\n[best] {best_name} selected (F1={best_metrics['f1']:.4f})")

    cm = confusion_matrix(y_test, best_model.predict(X_test_scaled)).tolist()

    joblib.dump(best_model, os.path.join(MODELS_DIR, "best_model.pkl"))
    joblib.dump(scaler, os.path.join(MODELS_DIR, "scaler.pkl"))

    feat_importance = plot_feature_importance(
        best_model, FEATURE_NAMES, os.path.join(STATIC_IMG_DIR, "feature_importance.png")
    )
    plot_comparison(results, os.path.join(STATIC_IMG_DIR, "model_comparison.png"))

    metadata = {
        "best_model": best_name,
        "feature_names": FEATURE_NAMES,
        "metrics_by_model": results,
        "best_metrics": best_metrics,
        "confusion_matrix": cm,
        "feature_importance": feat_importance,
        "train_rows": int(len(X_train)),
        "test_rows": int(len(X_test)),
        "xgboost_available": XGB_AVAILABLE,
        "lightgbm_available": LGBM_AVAILABLE,
    }
    with open(os.path.join(MODELS_DIR, "metadata.json"), "w") as f:
        json.dump(metadata, f, indent=2)

    print(f"\n[OK] Saved model -> models/best_model.pkl")
    print(f"[OK] Saved scaler -> models/scaler.pkl")
    print(f"[OK] Saved metadata -> models/metadata.json")


if __name__ == "__main__":
    main()
